services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    volumes:
      - ./backend:/app

    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    command: dotnet watch run --urls http://0.0.0.0:8080